import { XG_PER_SHOT_KPI, type XgTeamSideStats } from "./statystykiZespoluXgStats";

export type XgComparisonMetric = {
  key: string;
  label: string;
  hint?: string;
  teamValue: number;
  oppValue: number;
  teamDisplay: string;
  oppDisplay: string;
  unit?: "int" | "pct";
  signedValues?: boolean;
  showKpiLine?: boolean;
};

function pctDisplay(value: number, fmt2: (n: number) => string): string {
  return `${fmt2(value)}%`;
}

export function buildXgComparisonMetrics(
  teamStats: XgTeamSideStats,
  opponentStats: XgTeamSideStats,
  fmt2: (n: number) => string,
  formatSigned: (n: number) => string,
): XgComparisonMetric[] {
  return [
    {
      key: "total_xg",
      label: "xG łącznie",
      hint: "Suma expected goals",
      teamValue: teamStats.xg,
      oppValue: opponentStats.xg,
      teamDisplay: `${fmt2(teamStats.xg)} (${teamStats.shots} strz.)`,
      oppDisplay: `${fmt2(opponentStats.xg)} (${opponentStats.shots} strz.)`,
    },
    {
      key: "np_xg",
      label: "NP xG",
      hint: "xG bez rzutów karnych",
      teamValue: teamStats.npXg,
      oppValue: opponentStats.npXg,
      teamDisplay: `${fmt2(teamStats.npXg)} (${teamStats.shots - teamStats.penaltyShots} strz.)`,
      oppDisplay: `${fmt2(opponentStats.npXg)} (${opponentStats.shots - opponentStats.penaltyShots} strz.)`,
    },
    {
      key: "goals",
      label: "Gole",
      unit: "int",
      teamValue: teamStats.goals,
      oppValue: opponentStats.goals,
      teamDisplay: String(teamStats.goals),
      oppDisplay: String(opponentStats.goals),
    },
    {
      key: "xg_dominance",
      label: "Udział xG",
      hint: "Procent łącznej puli xG w meczu",
      unit: "pct",
      teamValue: teamStats.xgDominancePct,
      oppValue: opponentStats.xgDominancePct,
      teamDisplay: pctDisplay(teamStats.xgDominancePct, fmt2),
      oppDisplay: pctDisplay(opponentStats.xgDominancePct, fmt2),
    },
    {
      key: "efficiency",
      label: "Realizacja (G/xG)",
      hint: "Gole / xG × 100 — powyżej 100% = lepsza realizacja",
      unit: "pct",
      teamValue: teamStats.efficiencyPct,
      oppValue: opponentStats.efficiencyPct,
      teamDisplay: pctDisplay(teamStats.efficiencyPct, fmt2),
      oppDisplay: pctDisplay(opponentStats.efficiencyPct, fmt2),
    },
    {
      key: "np_efficiency",
      label: "NP realizacja",
      hint: "Gole bez karnych / NP xG × 100",
      unit: "pct",
      teamValue: teamStats.npEfficiencyPct,
      oppValue: opponentStats.npEfficiencyPct,
      teamDisplay: pctDisplay(teamStats.npEfficiencyPct, fmt2),
      oppDisplay: pctDisplay(opponentStats.npEfficiencyPct, fmt2),
    },
    {
      key: "xg_diff",
      label: "Różnica xG − gole",
      signedValues: true,
      teamValue: teamStats.xgDiff,
      oppValue: opponentStats.xgDiff,
      teamDisplay: formatSigned(teamStats.xgDiff),
      oppDisplay: formatSigned(opponentStats.xgDiff),
    },
    {
      key: "conversion",
      label: "Konwersja strzał→gol",
      unit: "pct",
      teamValue: teamStats.conversionPct,
      oppValue: opponentStats.conversionPct,
      teamDisplay: pctDisplay(teamStats.conversionPct, fmt2),
      oppDisplay: pctDisplay(opponentStats.conversionPct, fmt2),
    },
    {
      key: "xg_per_shot",
      label: "xG / strzał",
      hint: `KPI: ${fmt2(XG_PER_SHOT_KPI)}`,
      showKpiLine: true,
      teamValue: teamStats.xgPerShot,
      oppValue: opponentStats.xgPerShot,
      teamDisplay: fmt2(teamStats.xgPerShot),
      oppDisplay: fmt2(opponentStats.xgPerShot),
    },
    {
      key: "np_xg_per_shot",
      label: "NP xG / strzał",
      teamValue: teamStats.npXgPerShot,
      oppValue: opponentStats.npXgPerShot,
      teamDisplay: fmt2(teamStats.npXgPerShot),
      oppDisplay: fmt2(opponentStats.npXgPerShot),
    },
    {
      key: "open_play",
      label: "Otwarta gra",
      teamValue: teamStats.xgOpenPlay,
      oppValue: opponentStats.xgOpenPlay,
      teamDisplay: fmt2(teamStats.xgOpenPlay),
      oppDisplay: fmt2(opponentStats.xgOpenPlay),
    },
    {
      key: "counter",
      label: "Kontratak",
      teamValue: teamStats.xgCounter,
      oppValue: opponentStats.xgCounter,
      teamDisplay: `${fmt2(teamStats.xgCounter)} (${teamStats.counterShots})`,
      oppDisplay: `${fmt2(opponentStats.xgCounter)} (${opponentStats.counterShots})`,
    },
    {
      key: "sfg",
      label: "SFG",
      teamValue: teamStats.xgSfg,
      oppValue: opponentStats.xgSfg,
      teamDisplay: fmt2(teamStats.xgSfg),
      oppDisplay: fmt2(opponentStats.xgSfg),
    },
    {
      key: "regain",
      label: "Regain",
      teamValue: teamStats.xgRegain,
      oppValue: opponentStats.xgRegain,
      teamDisplay: fmt2(teamStats.xgRegain),
      oppDisplay: fmt2(opponentStats.xgRegain),
    },
    {
      key: "rebound",
      label: "Dobitki",
      hint: "Strzały z previousShotId",
      teamValue: teamStats.xgRebound,
      oppValue: opponentStats.xgRebound,
      teamDisplay: `${fmt2(teamStats.xgRebound)} (${teamStats.reboundShots})`,
      oppDisplay: `${fmt2(opponentStats.xgRebound)} (${opponentStats.reboundShots})`,
    },
    {
      key: "clean_xg",
      label: "Clean xG",
      hint: "Bez zawodnika na linii strzału",
      teamValue: teamStats.xgClean,
      oppValue: opponentStats.xgClean,
      teamDisplay: `${fmt2(teamStats.xgClean)} (${teamStats.cleanShots} strz., ${teamStats.goalsClean} g)`,
      oppDisplay: `${fmt2(opponentStats.xgClean)} (${opponentStats.cleanShots} strz., ${opponentStats.goalsClean} g)`,
    },
    {
      key: "assist_xg",
      label: "xG asyst",
      hint: "Suma xG bramek z asystą",
      teamValue: teamStats.assistXg,
      oppValue: opponentStats.assistXg,
      teamDisplay: `${fmt2(teamStats.assistXg)} (${teamStats.assistCount})`,
      oppDisplay: `${fmt2(opponentStats.assistXg)} (${opponentStats.assistCount})`,
    },
    {
      key: "avg_line",
      label: "Średnia zawodników na linii",
      teamValue: teamStats.avgLinePlayers,
      oppValue: opponentStats.avgLinePlayers,
      teamDisplay: fmt2(teamStats.avgLinePlayers),
      oppDisplay: fmt2(opponentStats.avgLinePlayers),
    },
    {
      key: "on_target_pct",
      label: "% celnych",
      unit: "pct",
      teamValue: teamStats.onTargetPct,
      oppValue: opponentStats.onTargetPct,
      teamDisplay: `${pctDisplay(teamStats.onTargetPct, fmt2)} (${teamStats.shotsOnTarget}/${teamStats.shots})`,
      oppDisplay: `${pctDisplay(opponentStats.onTargetPct, fmt2)} (${opponentStats.shotsOnTarget}/${opponentStats.shots})`,
    },
    {
      key: "gk_save_pct",
      label: "Obronione celne",
      hint: "Skuteczność bramkarza: celne strzały w bramkę (bez zablokowanych). Bramka = nieobroniony celny.",
      unit: "pct",
      teamValue: teamStats.gkSavePct,
      oppValue: opponentStats.gkSavePct,
      teamDisplay: `${pctDisplay(teamStats.gkSavePct, fmt2)} (${teamStats.gkSavesOnTarget} obr. / ${teamStats.gkOnTargetFaced} celnych, ${teamStats.gkGoalsConcededOnTarget} gol)`,
      oppDisplay: `${pctDisplay(opponentStats.gkSavePct, fmt2)} (${opponentStats.gkSavesOnTarget} obr. / ${opponentStats.gkOnTargetFaced} celnych, ${opponentStats.gkGoalsConcededOnTarget} gol)`,
    },
    {
      key: "blocked_pct",
      label: "% zablokowanych",
      unit: "pct",
      teamValue: teamStats.blockedPct,
      oppValue: opponentStats.blockedPct,
      teamDisplay: `${pctDisplay(teamStats.blockedPct, fmt2)} (${teamStats.shotsBlocked})`,
      oppDisplay: `${pctDisplay(opponentStats.blockedPct, fmt2)} (${opponentStats.shotsBlocked})`,
    },
    {
      key: "off_target_pct",
      label: "% niecelnych",
      unit: "pct",
      teamValue: teamStats.offTargetPct,
      oppValue: opponentStats.offTargetPct,
      teamDisplay: `${pctDisplay(teamStats.offTargetPct, fmt2)} (${teamStats.shotsOffTarget})`,
      oppDisplay: `${pctDisplay(opponentStats.offTargetPct, fmt2)} (${opponentStats.shotsOffTarget})`,
    },
    {
      key: "xg_blocked",
      label: "xG zablokowane",
      teamValue: teamStats.xgBlocked,
      oppValue: opponentStats.xgBlocked,
      teamDisplay: fmt2(teamStats.xgBlocked),
      oppDisplay: fmt2(opponentStats.xgBlocked),
    },
    {
      key: "xg_on_target",
      label: "xG celnych",
      teamValue: teamStats.xgOnTarget,
      oppValue: opponentStats.xgOnTarget,
      teamDisplay: `${fmt2(teamStats.xgOnTarget)} (${teamStats.shotsOnTarget}/${teamStats.shots})`,
      oppDisplay: `${fmt2(opponentStats.xgOnTarget)} (${opponentStats.shotsOnTarget}/${opponentStats.shots})`,
    },
    {
      key: "contact1_pct",
      label: "% 1T w strefie 1T",
      hint: "Strzały jednym kontaktem w pierwszej tercji",
      unit: "pct",
      teamValue: teamStats.contact1Pct,
      oppValue: opponentStats.contact1Pct,
      teamDisplay: pctDisplay(teamStats.contact1Pct, fmt2),
      oppDisplay: pctDisplay(opponentStats.contact1Pct, fmt2),
    },
    {
      key: "shots_1t",
      label: "Strefa 1T",
      unit: "int",
      teamValue: teamStats.shots1T,
      oppValue: opponentStats.shots1T,
      teamDisplay: `${teamStats.shots1T} (xG ${fmt2(teamStats.xg1T)})`,
      oppDisplay: `${opponentStats.shots1T} (xG ${fmt2(opponentStats.xg1T)})`,
    },
    {
      key: "xg_per_min",
      label: "xG / min pos.",
      teamValue: teamStats.xgPerMinPossession,
      oppValue: opponentStats.xgPerMinPossession,
      teamDisplay: `${fmt2(teamStats.xgPerMinPossession)} (${fmt2(teamStats.possessionMin)} min)`,
      oppDisplay: `${fmt2(opponentStats.xgPerMinPossession)} (${fmt2(opponentStats.possessionMin)} min)`,
    },
    {
      key: "xg_per_match_min",
      label: "xG / min meczu",
      teamValue: teamStats.xgPerMatchMin,
      oppValue: opponentStats.xgPerMatchMin,
      teamDisplay: `${fmt2(teamStats.xgPerMatchMin)} (${fmt2(teamStats.matchMinutes)} min)`,
      oppDisplay: `${fmt2(opponentStats.xgPerMatchMin)} (${fmt2(opponentStats.matchMinutes)} min)`,
    },
  ];
}
